export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_GROUP_LIST = 'SET_GROUP_LIST';
export const SET_FRIEND_LIST = 'SET_FRIEND_LIST';
export const SET_DIALOG_LIST = 'SET_DIALOG_LIST';